### ISSUE TITLE
user-mapping seems broken

### ISSUE THREAD

**Issue by nerdc0re-net** [dm-drogeriemarkt/Email-to-Confluence#2]
**Version**: Confluence 6.4.1
**Type**: Bug

-------------------
#### Description
user mapping from sender mail-addresses to confluence-users seems to be broken. pages only gets created as 'Anonymous'.

#### Steps to reproduce
1. send email to configured mail-address
2. check the created page

**Comment by gellweiler** [comment]
This is a confirmed bug with newer confluence versions.

`MessageParser::getSender()` will fail to get a valid user from e-mail, because `userAccessor.getUsersByEmail()` for some reason won't return a `ConfluenceUser` object. When saving the blog post one has to use an object of type `ConfluenceUser`. Verifying if the user is in a group will work with any `User` object tough, so sender verification will work.

Currently the following code in `MessageToBlogPostProcessor::process()`will set the user to anonymous (null) if the User object is not of type `ConfluenceUser`:

`post.setCreator((sender instanceof ConfluenceUser) ? (ConfluenceUser)sender : null);`

**Comment by gellweiler** [comment]
Fixed in Version 1.1.
